config/routes.rb
Rails.application.routes.draw do
  get "reviews/create"
  get "reviews/new"
  # # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # # Defines the root path route ("/")
  # # root "posts#index"
# get "lists", to: "lists#index"
# get "lists/:id", to: "lists#show", as :list
# get "lists/new", to: "lists#new"
# post "lists", to: "lists#create"

  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:create, :new]
  end

  get "bookmarks/:id", to: "bookmarks#show", as: :bookmark
  delete "bookmarks/:id", to: "bookmarks#destroy", as: :destroy_bookmark
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6 }
  validates :movie_id, :list_id, presence: true
  validates :movie_id, uniqueness: { scope: :list_id, message: "has already been added to this list" }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true, length: { minimum: 1 }
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  has_many :reviews
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :overview, uniqueness: true, length: { minimum: 1 }
  has_many :bookmarks

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list
    else
      flash[:alert] = "Something went wrong"
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.list
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]


  def index
    @lists = List.all
  end

  def show

  end

  def new
    @list = List.new
  end

  def update
    @list.update(list_params)
    redirect_to @list
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :image, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    set_list
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    set_list
    @review = Review.new
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_form_bookmarks.html.erb
  <%= simple_form_for @bookmark, url: list_bookmarks_path(@list) do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.button :submit %>
  <% end %>

app/views/bookmarks/new.html.erb
<div class="container mt-5 ">
  <h1>Add a new bookmark to the "<%= @list.name %>" list</h1>
  <%= render "form_bookmarks", bookmark: @bookmark %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Watch List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light justify-content-between px-3">
      <%= link_to "Home", lists_path, class: "navbar-brand", type: "button" %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Add List", new_list_path, class: "btn btn-primary" %>
        </li>
      </ul>
    </nav>




    <%= yield %>
  </body>
</html>

app/views/lists/_card.html.erb
<div class="card mb-4 shadow">
  <%= link_to list_path(list), class: "text-decoration-none" do %>
    <div class="card-body d-flex align-items-center justify-content-center">
      <h5 style="color: black; font-family: Arial, sans-serif; margin-bottom: 0px;"><%= list.name %></h5>
    </div>
    <div class="card-body bg-light object-fit-fill" id="card-main" style="background-image: url('<%= cl_image_path list.photo.key %>'); height: 200px; background-size: cover; background-position: center;">
    </div>
  <% end %>
</div>

app/views/lists/_form.html.erb
<%= simple_form_for (@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>

  <%= f.button :submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing <%= @list.name %></h1>

<%= render "form", list: @list %>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1595769816263-9b910be24d5f?q=80&w=2079&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="container d-flex align-items-center justify-content-center">
    <div>
      <h1>Save any kind of movies</h1>
      <h2>These are your lists</h2>
    </div>
  </div>
</div>
<div class="container mt-5">
  <h1>Lists</h1>
  <div class="row mt-4">
    <% @lists.each do |list| %>
      <div class="col-md-4">
        <%= render "card", list: list %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container mt-5 ">
  <h1>New List</h1>
  <%= render "form", list: @list %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key %>');">
  <div class="d-flex align-items-center justify-content-center">
    <h1><%= @list.name %></h1>
  </div>
</div>



<div class="container mt-5 ">
  <div class="d-flex justify-content-between p-3">
    <h1>Movies</h1>
    <%= link_to "Add Bookmark", new_list_bookmark_path(@list), class: "btn btn-primary d-flex align-items-center justify-content-center", style: "font-size: 23px" %>
  </div>
  <div class="row">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow" style="background-color: #eee; width: 400px; height: 500px;">
          <%# Card Main %>
          <div class="card-body bg-light object-fit-fill" id="card-main" style="background-image: url('<%= bookmark.movie.poster_url %>'); height: 200px; background-size: cover; background-position: center;">
          </div>

          <%# Info Card %>
          <div class="p-3" id="info-card" style="height: 120px; overflow: hidden;">
            <h5><%= bookmark.movie.title %> - <%= bookmark.movie.rating %> 🌟</h5>
            <p><%= bookmark.movie.overview %></p>
          </div>

          <%# Comment Card %>
          <div class="d-flex justify-content-between p-3" id="comment-card" style="height: 100px;">
            <%# Comment %>
            <p class="m-0" style="flex: 2; overflow: hidden; text-overflow: ellipsis; padding-right: 1rem;">
              <i class="fa-solid fa-quote-left"></i> <%= " " %> <%= bookmark.comment %>
            </p>
            <%# Button %>
            <%= link_to "Delete this bookmark", bookmark_path(bookmark),
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
              class: "btn btn-secondary text-decoration-none d-flex align-items-center justify-content-center",
              style: "flex: 1;" %>
          </div>
        </div>
      </div>
    <% end %>




  </div>


  <div class="d-flex justify-content-between p-3 mt-5">
    <h1>Reviews</h1>
    <%= link_to "Add a Review", new_list_review_path(@list), class: "btn btn-primary d-flex align-items-center justify-content-center", style: "font-size: 23px" %>
  </div>

  <div class="row">
    <% @list.reviews.each do |review| %>
      <div class="card mb-4 shadow d-flex justify-content-between p-3 " style="background-color: #eee" id="review-card">
        <p style="margin-bottom: 0px"><i class="fa-solid fa-quote-left"></i> <%= " " %><%= review.content %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_form_reviews.html.erb
  <%= simple_form_for @review, url: list_reviews_path(@list) do |f| %>
    <%= f.input :content %>
    <%= f.button :submit %>
  <% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container mt-5 ">
  <h1>Review <%= @list.name %></h1>

  <%= render "form_reviews", review: @review %>
</div>